{% set version = "0.0" %}
package:
  name: resonant_lsm
  version: {{ version }}

source:
  git_url: https://github.com/siboles/resonant_lsm.git
  git_rev: v{{ version }}

build:
  script: cd src; {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - vtk >=9.0
    - simpleitk >=2.0
    - pyyaml >=5.4
    - numpy >=1.21

test:
  imports:
    - resonant_lsm.segmenter

about:
  home: https://github.com/siboles/resonant_lsm
  summary: A package for object segmentation from 3-D laser scanning microscopy images;
           particularly, those obtained with resonance scanning.
  license: BSD-3 License
